name: 'Get parameter from AWS SSM'
description: 'Get parameter from AWS SSM reusable action'
author: 'Gutenberg Technology'


inputs:
  secret:
    description: 'Secret parameter name'
    required: true
  region:
    description: 'AWS region'
    required: true
    default: 'us-east-1'
  aws-access-key-id:
    description: 'AWS access key id'
    required: true 
  aws-secret-access-key:
    description: 'AWS secret access key'
    required: true  
  
runs:
  using: 'composite'
  steps:
    - name: Configure AWS credentials
      id: aws-credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.AWS_REGION }}

    - name: 'Get parameter'
      id: get-parameter
      uses: 'aws-actions/aws-cli@v1'
      with:
        args: 'ssm get-parameter --name ${{ inputs.secret }} --region ${{ inputs.region }} --query "Parameter.Value" --output text'
 
    - name: 'Set output'
      run: echo "parameter-value=${{ steps.get-parameter.outputs.stdout }}" >> $GITHUB_ENV
      shell: bash