name: 'Get parameter from AWS SSM'
description: 'Get parameter from AWS SSM reusable action'
author: 'Gutenberg Technology'


inputs:
  parameter-pairs:
    description: 'Secret parameter name list'
    required: true
  aws-region:
    description: 'AWS region'
    required: true
    default: 'us-east-1'
  aws-access-key-id:
    description: 'AWS access key id'
    required: true 
  aws-secret-access-key:
    description: 'AWS secret access key'
    required: true  
  
runs:
  using: 'composite'
  steps:
    - name: Configure AWS credentials
      id: aws-credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Get parameters
      id: get-parameter
      uses: dkershner6/aws-ssm-getparameters-action@v2
      with:
        parameterPairs: ${{ inputs.parameter-pairs }}
      # The part before equals is the ssm parameterName, and after is the ENV Variable name for the workflow.
      # No limit on number of parameters. You can put new lines and spaces in as desired, they get trimmed out.
      withDecryption: "false" # defaults to true
 
    - name: 'Set output'
      run: echo "parameter-value=${{ steps.get-parameter.outputs.stdout }}" >> $GITHUB_ENV
      shell: bash